CREATE SEQUENCE shop_owner."USER_SEQ"
    INCREMENT BY 1
    START WITH 10000
    MINVALUE 10000
    MAXVALUE 10000000
    NOCYCLE
    CACHE 2
;

CREATE TABLE "USER"
(
    "ID" NUMBER(19,0) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) NOT NULL,
    "EXPIRY_DATE" TIMESTAMP(6),
    primary key("ID")
);
